export const COLLABORATIONS = {
    brands: [
      'AnnóAnnó',
      'Creademic',
      '(Di)vision',
      'Good Statement',
      'Lala Berlin',
      'Le Management',
      'Libertine Libertine',
      'Loréal Paris',
      'NH Collection',
      'Nomad',
      'Ole Lynggaard',
      'Pandora',
      'Rimmel London',
      'Sophia Khaled',
      'Won Hundred',
      '66 North',
    ],
    music: [
      'Univeral Music',
      'Sony Music',
      'Warner Music',
      'Anthon Edwards',
      'Bathsheba',
      'Blæst',
      'Danser med Piger',
      'DJ Lilli',
      'Ericka Jane',
      'Iris Gold',
      'PÍL',
      'Rósel',
      'Saba',
      'Sebastican Bull',
      'Selma Higgins',
      'Stundom',
      'Troels Gustavson',
    ],
    magazines: [
      'Alt for Damerne',
      'COSTUME DK',
      'Vouge Scandinavia',
      'Vangouard',
    ],
    events: [
      'Echo Prisen',
      'Copenhagen Fashion Week',
      'French Brands Nordic',
      'Voice Radio Awards',
    ],
    tvFilm: [
      'ViaPlay / TV3',
      'Champions League',
      'Premiere League',
      'Superliga',
      'Formula 1',
      'Kvindelandsholdet',
      'VM Kvindefodbold',
      'Warner Bros Studios',
    ],
    fashionWeek: [
      'Aeron Studio',
      'Baum Und Pferdgarten',
      '(Di)vision',
      'Helmstedt',
      'Joao Maraschin',
      'MKDT Studio',
      'Masculina',
      'Munthe',
      'Tg Botanical',
      'The Garment',
      'Holsweiler',
      'Selected',
      'Stamm Exchange'
    ],
};