export const GALLERY_IMAGES = [
    'IMG_2688_jgjtcw',
    'IMG_2108_wbkhtz',
    'IMG_2106_sxt1zj',
    'mm01_mo86gy',
    'mm02_xekwd4',
    'mm03_bolajj',
    'mm04_p3rbew',
    'mm05_tgaajh',
    'mm06_msds2p',
    'mm07_becfbd',
    'mm08_r8qehl',
];

export const PROJECTS = [
    {
      id: 'leblue-magazine',
      title: 'LEBLUE MAGAZINE',
      coverImage: 'lbm01_msv5sg',
      images: ['lbm01_msv5sg', 'lbm02_jlhckc', 'lbm03_ulvf6v', 'lbm04_srvbks', 'lbm05_dpeklx'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'nomad-x-marie-jedig',
      title: 'NOMAD X MARIE JEDIG',
      coverImage: 'nxm01_siwyft',
      images: ['nxm01_siwyft', 'nxm02_zcamk8', 'nxm03_vb9o7y', 'nxm04_cqsxoz', 'nxm05_xpdydz', 'nxm06_lawbtg', 'nxm07_m8qwl5', 'nxm08_gbbux9', 'nxm09_zmcfej', 'nxm10_hosygo', 'nxm11_fx0bia', 'nxm12_gmopih', 'nxm13_sjnyg3', 'nxm14_r3xel4', 'nxm15_wb8hy5', 'nxm16_flgisq', 'nxm17_ofuzrs'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'the-garment',
      title: 'THE GARMENT',
      coverImage: 'gmt01_g1qjdi',
      images: ['gmt01_g1qjdi', 'gmt02_pfmopb', 'gmt03_adjyep', 'gmt04_qptqay'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'rosel',
      title: 'RÓSEL',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'photo-vogue',
      title: 'PHOTO VOGUE',
      coverImage: 'mm07_becfbd',
      images: ['IMG_2688_jgjtcw', 'IMG_2108_wbkhtz', 'IMG_2106_sxt1zj'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'annoanno-aw24',
      title: 'ANNÓANNÓ AW24',
      coverImage: 'mm07_becfbd',
      images: ['mm01_mo86gy', 'mm02_xekwd4', 'mm03_bolajj'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'costume-dk',
      title: 'COSTUME DK',
      coverImage: 'cost01_evfplg',
      images: ['cost01_evfplg', 'cost02_z4wrsr', 'cost03_h8eeiu', 'cost04_py3qld'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'jasmin',
      title: 'JASMIN',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'stamm-exchange',
      title: 'STAMM EXCHANGE',
      coverImage: 'mm07_becfbd',
      images: ['IMG_2688_jgjtcw', 'IMG_2108_wbkhtz', 'IMG_2106_sxt1zj'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'photo-vogue-2',
      title: 'PHOTO VOGUE',
      coverImage: 'mm07_becfbd',
      images: ['mm01_mo86gy', 'mm02_xekwd4', 'mm03_bolajj'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'stundom',
      title: 'STUNDOM',
      coverImage: 'mm07_becfbd',
      images: ['mm04_p3rbew', 'mm05_tgaajh', 'mm06_msds2p'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'troels-gustavsen',
      title: 'TROELS GUSTAVSEN',
      coverImage: 'tro01_lnyyno',
      images: ['tro01_lnyyno', 'tro02_fa3swu', 'tro03_iij59e', 'tro04_xc8nra', 'tro05_l4rmpj', 'tro06_xt3wkw', 'tro07_mpxcvy', 'tro08_khvuwl', 'tro09_sjwkvk', 'tro10_r9qoa4', 'tro11_ieje1t', 'tro12_mffmpp'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'anthon-edwards',
      title: 'ANTHON EDWARDS',
      coverImage: 'aed01_x8go6b',
      images: ['aed01_x8go6b'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'kanya',
      title: 'KANYA',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'sophia-khaled',
      title: 'SOPHIA KHALED',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'meredith',
      title: 'MEREDITH',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'nanna',
      title: 'NANNA',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'annoanno-ss24',
      title: 'ANNÓANNÓ SS24',
      coverImage: 'mm07_becfbd',
      images: ['mm07_becfbd', 'mm08_r8qehl'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'vanguard-magazine',
      title: 'VANGUARD MAGAZINE',
      coverImage: 'vng02_hbtwbw',
      images: ['vng02_hbtwbw', 'vng01_svyt8s', 'vng03_zsuo2m', 'vng04_r3nmab', 'vng05_zsb9ho', 'vng06_gvb83y', 'vng07_zppuen', 'vng08_jrm6rn', 'vng09_kxfyqx', 'vng10_q9vezg', 'vng11_ea991m', 'vng12_yd7wdd', 'vng13_d16o3u', 'vng14_bmnlq6', 'vng15_x0kyas', 'vng16_yhikhp', 'vng17_x4vcrg', 'vng18_znpkfw', 'vng19_vqsknt', 'vng20_udfo8y', 'vng21_wdpumg', 'vng22_kb8wh9', 'vng23_bmxbfb', 'vng24_s1pfhr', 'vng25_bxqg3k'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
    {
      id: 'libertine-libertine',
      title: 'LIBERTINE LIBERTINE',
      coverImage: 'lib01_nauwmb',
      images: ['lib01_nauwmb', 'lib02_vz7xha', 'lib03_hhogej', 'lib04_st423i','lib05_k9jlna'],
      photographer: 'distilledpaper',
      model: 'kanyawhussy',
      hmua: 'teklakristjans',
    },
];

export const BRIDAL_IMAGES = [
    'IMG_2688_jgjtcw', // Replace
    'IMG_2108_wbkhtz',
    'IMG_2106_sxt1zj',
    'mm01_mo86gy',
    'mm02_xekwd4',
    'mm03_bolajj',
    'mm04_p3rbew',
    'mm05_tgaajh',
    'mm06_msds2p',
    'mm07_becfbd',
    'mm08_r8qehl',
];
